### ISSUE TITLE
Support for 5.6.x version?

### ISSUE THREAD

**Issue by bharathphatak** [lmangani/kibana_graph#3]
Hi Team,

Does this support 5.6.x version of kibana ?

**Comment by lmangani** [comment]
@bharathphatak yeah, it should work fine with 5.6 just by adjusting the plugin version

**Comment by lmangani** [comment]
Try as follows, replace `5.6.1` with the target version:
```
VERSION="5.6.1" ./release.sh
```

**Comment by karnamonkster** [comment]
Hi, Sorry for picking up a closed thread but it seems the changing of version does not work.
I am trying this on v 5.6.2
I changed it on both the files 
release.sh & package.json 
Getting the error when i try to start kibana
![graph_error](https://user-images.githubusercontent.com/5524898/44196098-0ea3c380-a14c-11e8-9145-1ca9b1f0c50e.PNG)

**Comment by lmangani** [comment]
Hi @bharathphatak please check for errors in the Kibana logs as you run or install the plugin

**Comment by karnamonkster** [comment]
This works now 
thanks.

**Comment by bharathphatak** [comment]
@lmangani Thanks. It worked by just changing version
